print("# generated by mBlock5 for ESP32 Micropython\
# download and install Micropython firmware from https://micropython.org/download/esp32/")

import machine, neopixel, time

GPIO_pin_number_4 = machine.Pin(4)
light_leds_number = 15
ledstrip = neopixel.NeoPixel(GPIO_pin_number_4, light_leds_number)

def transition(source_color, dest_color, seconds, led_num):
    tick = 0.01
    steps = int(seconds // tick)
    for i in range(steps):
        for led_index in range(led_num):
            current_color = middle(source_color, dest_color, steps, i)
            ledstrip[led_index] = current_color
            ledstrip.write()
        time.sleep(tick)

def middle(origin, destination, steps, index):
    return (origin[0] + round(((destination[0] - origin[0]) / steps) * index),
            origin[1] + round(((destination[1] - origin[1]) / steps) * index),
            origin[2] + round(((destination[2] - origin[2]) / steps) * index))

for i in range(0, 14+1):
    ledstrip[i] = (0, 0, 0)
ledstrip.write()
for count in range(5):
    for i in range(len(ledstrip)):
        ledstrip[i] = (0,0,0)
    ledstrip.write()
    transition((255,0,0), (255,255,0), 1, 15)
    for i in range(len(ledstrip)):
        ledstrip[i] = (0,0,0)
    ledstrip.write()
    transition((255,255,0), (0,255,0), 1, 15)
    for i in range(len(ledstrip)):
        ledstrip[i] = (0,0,0)
    ledstrip.write()
    transition((0,255,0), (0,255,255), 1, 15)
    for i in range(len(ledstrip)):
        ledstrip[i] = (0,0,0)
    ledstrip.write()
    transition((0,255,255), (0,0,255), 1, 15)
    for i in range(len(ledstrip)):
        ledstrip[i] = (0,0,0)
    ledstrip.write()
    transition((0,0,255), (255,0,255), 1, 15)
    for i in range(len(ledstrip)):
        ledstrip[i] = (0,0,0)
    ledstrip.write()
    transition((255,0,255), (255,0,0), 1, 15)

